[package]
name = "aule-python"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
name = "aule_python"
crate-type = ["rlib"]
path = "src/lib.rs"

[features]
default = []

[dependencies]


