[package]
name = "viewer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
winit.workspace = true
wgpu.workspace = true
egui.workspace = true
pollster.workspace = true
engine = { path = "../engine" }


