[book]
title = "Aulë — Procedural Tectonics"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/Cradoux/aule"
site-url = "/aule/"
additional-css = []

