name: Docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.79.0
          components: rustfmt

      - name: Tool versions
        run: |
          rustc -Vv
          cargo -V
          rustfmt -V || true

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: mdBook version
        run: mdbook -V

      - name: Build docs
        run: mdbook build docs

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/book
          force_orphan: true

